import 'package:flutter/material.dart';

import '../../core/theme.dart';
import '../../widgets/moon_widget.dart';
import '../../widgets/primary_button.dart';
import '../../widgets/star_background.dart';

class WelcomeScreen extends StatelessWidget {
  const WelcomeScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                backgroundColor: AppTheme.background,
                      body: Stack(
                              children: [
                                        const Positioned.fill(
                                                    child: StarBackground(),
                                                              ),

                                                                        SafeArea(
                                                                                    child: Padding(
                                                                                                  padding: const EdgeInsets.symmetric(
                                                                                                                  horizontal: 28,
                                                                                                                                  vertical: 24,
                                                                                                                                                ),
                                                                                                                                                              child: Column(
                                                                                                                                                                              children: [
                                                                                                                                                                                                const Spacer(),

                                                                                                                                                                                                                  const MoonWidget(),

                                                                                                                                                                                                                                    const SizedBox(height: 40),

                                                                                                                                                                                                                                                      const Text(
                                                                                                                                                                                                                                                                          "LumiNest",
                                                                                                                                                                                                                                                                                              textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                  style: TextStyle(
                                                                                                                                                                                                                                                                                                                                        fontSize: 42,
                                                                                                                                                                                                                                                                                                                                                              fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                    color: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                                                                                              const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Build your little world together.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: Colors.white70,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            height: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const Spacer(),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      PrimaryButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          text: "Start Your Journey",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }