import 'package:flutter/material.dart';

import '../../core/theme.dart';
import '../../widgets/custom_bottom_navigation.dart';
import '../../widgets/glass_card.dart';
import '../../widgets/info_tile.dart';
import '../../widgets/section_title.dart';
import '../../widgets/star_background.dart';
import '../../widgets/hero_card.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

    @override
      State<HomeScreen> createState() => _HomeScreenState();
      }

      class _HomeScreenState extends State<HomeScreen> {
        int _selectedIndex = 0;

          @override
            Widget build(BuildContext context) {
                return Scaffold(
                      backgroundColor: AppTheme.background,
                            body: Stack(
                                    children: [
                                              const Positioned.fill(
                                                          child: StarBackground(),
                                                                    ),
                                                                              SafeArea(
                                                                                          child: ListView(
                                                                                                        padding: const EdgeInsets.all(24),
                                                                                                                      children: [
                                                                                                                                      const SectionTitle(
                                                                                                                                                        title: "Welcome Back 💜",
                                                                                                                                                                          subtitle: "Let's create beautiful memories together.",
                                                                                                                                                                                          ),

                                                                                                                                                                                          const SizedBox(height: 20),
                                                                                                                                                                                          
                                                                                                                                                                                          const HeroCard(),
                                                                                                                                                                                          
                                                                                                                                                                                          const SizedBox(height: 24),                const SizedBox(height: 20),

                                                                                                                                                                                                                          GlassCard(
                                                                                                                                                                                                                                            child: const InfoTile(
                                                                                                                                                                                                                                                                icon: Icons.favorite_rounded,
                                                                                                                                                                                                                                                                                    iconColor: Colors.pink,
                                                                                                                                                                                                                                                                                                        title: "Family",
                                                                                                                                                                                                                                                                                                                            subtitle: "Stay connected with your loved ones.",
                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                              ),

                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                              GlassCard(
                                                                                                                                                                                                                                                                                                                                                                                                                child: const InfoTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                    icon: Icons.child_care,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        iconColor: Colors.deepPurpleAccent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: "Children",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                subtitle: "Track growth and milestones.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                const SizedBox(height: 16),

                                GlassCard(
                                                  child: const InfoTile(
                                                                      icon: Icons.photo_library_rounded,
                                                                                          iconColor: Colors.amber,
                                                                                                              title: "Memories",
                                                                                                                                  subtitle: "Relive your favorite family moments.",
                                                                                                                                                    ),
                                                                                                                                                                    ),

                                                                                                                                                                                    const SizedBox(height: 16),

                                                                                                                                                                                                    GlassCard(
                                                                                                                                                                                                                      child: const InfoTile(
                                                                                                                                                                                                                                          icon: Icons.event_note_rounded,
                                                                                                                                                                                                                                                              iconColor: Colors.cyan,
                                                                                                                                                                                                                                                                                  title: "Planner",
                                                                                                                                                                                                                                                                                                      subtitle: "Stay on top of your daily plans.",
                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                        ),

                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 30),

                                                                                                                                                                                                                                                                                                                                                                        GlassCard(
                                                                                                                                                                                                                                                                                                                                                                                          child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                              crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                                                                                                                                                                                                                                                                                                                  children: const [
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Today's Quote",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "\"The little moments become the big memories.\"",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: Colors.white70,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                const SizedBox(height: 32),
                              ],
                                          ),
                                                    ),
                                                            ],
                                                                  ),
                                                                        bottomNavigationBar: CustomBottomNavigation(
                                                                                currentIndex: _selectedIndex,
                                                                                        onTap: (index) {
                                                                                                  setState(() {
                                                                                                              _selectedIndex = index;
                                                                                                                        });
                                                                                                                                },
                                                                                                                                      ),
                                                                                                                                          );
                                                                                                                                            }
                                                                                                                                            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  