import 'dart:ui';

import 'package:flutter/material.dart';

class GlassCard extends StatelessWidget {
  final Widget child;
    final VoidCallback? onTap;
      final EdgeInsetsGeometry padding;
        final double borderRadius;

          const GlassCard({
              super.key,
                  required this.child,
                      this.onTap,
                          this.padding = const EdgeInsets.all(20),
                              this.borderRadius = 24,
                                });

                                  @override
                                    Widget build(BuildContext context) {
                                        return ClipRRect(
                                              borderRadius: BorderRadius.circular(borderRadius),
                                                    child: BackdropFilter(
                                                            filter: ImageFilter.blur(
                                                                      sigmaX: 18,
                                                                                sigmaY: 18,
                                                                                        ),
                                                                                                child: Material(
                                                                                                          color: Colors.transparent,
                                                                                                                    child: InkWell(
                                                                                                                                borderRadius: BorderRadius.circular(borderRadius),
                                                                                                                                            onTap: onTap,
                                                                                                                                                        child: Ink(
                                                                                                                                                                      decoration: BoxDecoration(
                                                                                                                                                                                      color: const Color(0xFF1C2340).withOpacity(0.45),
                                                                                                                                                                                                      borderRadius: BorderRadius.circular(borderRadius),
                                                                                                                                                                                                                      border: Border.all(
                                                                                                                                                                                                                                        color: Colors.white.withOpacity(0.10),
                                                                                                                                                                                                                                                          width: 1.2,
                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                          boxShadow: [
                                                                                                                                                                                                                                                                                                            BoxShadow(
                                                                                                                                                                                                                                                                                                                                color: Colors.black.withOpacity(0.18),
                                                                                                                                                                                                                                                                                                                                                    blurRadius: 20,
                                                                                                                                                                                                                                                                                                                                                                        offset: const Offset(0, 10),
                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: padding,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: child,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }