import 'package:flutter/material.dart';

class HeroCard extends StatelessWidget {
  const HeroCard({super.key});

    @override
      Widget build(BuildContext context) {
          return Container(
                width: double.infinity,
                      padding: const EdgeInsets.all(24),
                            decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(28),
                                            gradient: const LinearGradient(
                                                      begin: Alignment.topLeft,
                                                                end: Alignment.bottomRight,
                                                                          colors: [
                                                                                      Color(0xFF4B3CF0),
                                                                                                  Color(0xFF7A5CFA),
                                                                                                            ],
                                                                                                                    ),
                                                                                                                            boxShadow: const [
                                                                                                                                      BoxShadow(
                                                                                                                                                  color: Color(0x33000000),
                                                                                                                                                              blurRadius: 20,
                                                                                                                                                                          offset: Offset(0, 10),
                                                                                                                                                                                    ),
                                                                                                                                                                                            ],
                                                                                                                                                                                                  ),
                                                                                                                                                                                                        child: Column(
                                                                                                                                                                                                                crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                  const Text(
                                                                                                                                                                                                                                              "🌙 Good Evening",
                                                                                                                                                                                                                                                          style: TextStyle(
                                                                                                                                                                                                                                                                        color: Colors.white70,
                                                                                                                                                                                                                                                                                      fontSize: 15,
                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 8),
                                                                                                                                                                                                                                                                                                                                const Text(
                                                                                                                                                                                                                                                                                                                                            "Welcome Back",
                                                                                                                                                                                                                                                                                                                                                        style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                      color: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 30,
                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 24),
                                                                                                                                                                                                                                                                                                                                                                                                                                            Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: 58,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      height: 58,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      decoration: BoxDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: Colors.white.withOpacity(.15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: const Icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Icons.wb_twilight_rounded,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: Colors.amber,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                size: 32,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(width: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "22°C",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "Clear Sky",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: Colors.white70,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }