import 'package:flutter/material.dart';

class InfoTile extends StatelessWidget {
  final IconData icon;
    final Color iconColor;
      final String title;
        final String subtitle;
          final VoidCallback? onTap;
            final Widget? trailing;

              const InfoTile({
                  super.key,
                      required this.icon,
                          required this.iconColor,
                              required this.title,
                                  required this.subtitle,
                                      this.onTap,
                                          this.trailing,
                                            });

                                              @override
                                                Widget build(BuildContext context) {
                                                    return InkWell(
                                                          borderRadius: BorderRadius.circular(18),
                                                                onTap: onTap,
                                                                      child: Padding(
                                                                              padding: const EdgeInsets.symmetric(vertical: 4),
                                                                                      child: Row(
                                                                                                children: [
                                                                                                            Container(
                                                                                                                          width: 54,
                                                                                                                                        height: 54,
                                                                                                                                                      decoration: BoxDecoration(
                                                                                                                                                                      color: iconColor.withOpacity(.15),
                                                                                                                                                                                      borderRadius: BorderRadius.circular(16),
                                                                                                                                                                                                    ),
                                                                                                                                                                                                                  child: Icon(
                                                                                                                                                                                                                                  icon,
                                                                                                                                                                                                                                                  color: iconColor,
                                                                                                                                                                                                                                                                  size: 28,
                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                        const SizedBox(width: 16),

                                                                                                                                                                                                                                                                                                                    Expanded(
                                                                                                                                                                                                                                                                                                                                  child: Column(
                                                                                                                                                                                                                                                                                                                                                  crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                                                                                                                                    Text(
                                                                                                                                                                                                                                                                                                                                                                                                        title,
                                                                                                                                                                                                                                                                                                                                                                                                                            style: const TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: Colors.white,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 17,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontWeight: FontWeight.w700,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            subtitle,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: Colors.white.withOpacity(.65),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        trailing ??
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const Icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Icons.arrow_forward_ios_rounded,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: Colors.white38,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              size: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }